from __future__ import annotations

import json
import os
from typing import Annotated, Any, Dict

import pandas as pd
from langchain_community.vectorstores import FAISS
from langchain_oci.chat_models.oci_generative_ai import ChatOCIGenAI
from langchain_oci.embeddings import OCIGenAIEmbeddings
from pydantic import BaseModel, Field


# -----------------------------
# Pydantic input schemas
# -----------------------------


class RetrievalInput(BaseModel):
    query: Annotated[str, Field(..., description="Natural language query to retrieve relevant docs/schema snippets.")]

class RunSQLInput(BaseModel):
    sql: Annotated[str, Field(..., description="Spark SQL query to run against the Delta Lake database.")]

class VisualizeInput(BaseModel):
    csv_path: Annotated[str, Field(..., description="Path to the CSV artifact generated by the latest run_sql tool call.")]
    chart_type: Annotated[str, Field(..., description="Chart type to generate: 'bar'|'line'|'pie'.")]
    x: Annotated[str, Field(..., description="Column name to use for x-axis labels or pie labels.")]
    y: Annotated[str, Field(..., description="Column name to use for y-axis values.")]


# -----------------------------
# Tool implementations
# -----------------------------


class ToolsManager:
    def __init__(self, profile_name: str = "bmc-sie-prod"):
        self.profile_name = profile_name
        self.authenticate()
        self.initialize_clients()

    def authenticate(self):
        os.system(
            "oci session authenticate --profile-name bmc-sie-prod "
            "--region us-ashburn-1 --tenancy-name bmc_operator_access --auth security_token"
        )

    def initialize_clients(self):
        # Local import to avoid import-time side effects for clients.
        try:
            from delta_ai_chat.conn_dataflow import DataflowConnector
        except ImportError:
            from conn_dataflow import DataflowConnector

        self.oc1_delta_conn = DataflowConnector(self.profile_name)

        # LLM used for formatting SQL results into strict JSON
        self.llm = ChatOCIGenAI(
            model_id="ocid1.generativeaimodel.oc1.iad.amaaaaaask7dceyargceyuaysrjzo2metq2rinavayxqmpu7tkm6mmfojcvq",  # gemini pro
            service_endpoint="https://inference.generativeai.us-ashburn-1.oci.oraclecloud.com",
            compartment_id="ocid1.tenancy.oc1..aaaaaaaat3gxqmhzhjniz6udhx6ak6nngup2quzdahdztnhl7p4oznurigfq",
            auth_type="SECURITY_TOKEN",
            auth_profile=self.profile_name,
            provider="generic",
            model_kwargs={"temperature": 0, "top_k": 1, "top_p": 0.1},
        )

        self.embeddings = OCIGenAIEmbeddings(
            model_id="cohere.embed-english-v3.0",
            service_endpoint="https://inference.generativeai.uk-london-1.oci.oraclecloud.com",
            compartment_id="ocid1.compartment.oc1..aaaaaaaaac64gw2jhiwemjswhxb5odbwpaktqxt5ublisya2uotjn7g6wxqa",
            model_kwargs={"truncate": True},
            auth_type="SECURITY_TOKEN",
            auth_profile=self.profile_name,
        )

        base_dir = os.path.dirname(os.path.abspath(__file__))
        self.vectorstore = FAISS.load_local(
            os.path.join(base_dir, "vectorstore"),
            embeddings=self.embeddings,
            allow_dangerous_deserialization=True,
        )
        self.retriever = self.vectorstore.as_retriever(search_kwargs={"k": 5})

    def _execute_query(self, sql_query: str) -> str:
        """
        Executes SQL and returns a JSON string.

        Success:
          {
            "status": "ok",
            "type": "table",
            "format": "csv",
            "csv_path": ".../artifacts/<file>.csv",
            "csv_filename": "<file>.csv",
            "columns": [...],
            "row_count": N
          }

        Error:
          {
            "status": "error",
            "error_message": "..."
          }
        """
        try:
            self.oc1_delta_conn.check_connection()
            data_obj = self.oc1_delta_conn.pull_data(sql_query)
            return self._persist_table_result(data_obj)

        except Exception as e:
            error_str = str(e)
            if "401" in error_str:
                self.authenticate()
                self.initialize_clients()
                try:
                    self.oc1_delta_conn.check_connection()
                    data_obj = self.oc1_delta_conn.pull_data(sql_query)
                    return self._persist_table_result(data_obj)
                except Exception as retry_e:
                    return json.dumps({"status": "error", "error_message": str(retry_e)})
            return json.dumps({"status": "error", "error_message": error_str})

    def _persist_table_result(self, data_obj: Dict[str, Any]) -> str:
        """
        Takes the normalized JSON output (columns/rows)
        and persists it to a CSV artifact file. Returns an artifact JSON string.
        """
        try:
            columns = data_obj.get("columns", [])
            rows = data_obj.get("rows", [])

            artifacts_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "artifacts")
            os.makedirs(artifacts_dir, exist_ok=True)

            filename = f"run_sql_{pd.Timestamp.utcnow().strftime('%Y%m%d_%H%M%S')}_{os.urandom(4).hex()}.csv"
            csv_path = os.path.join(artifacts_dir, filename)

            df = pd.DataFrame(rows, columns=columns)
            df.to_csv(csv_path, index=False)

            return json.dumps(
                {
                    "status": "ok",
                    "type": "table",
                    "format": "csv",
                    "csv_path": csv_path,
                    "csv_filename": filename,
                    "columns": columns,
                    "row_count": len(rows),
                }
            )
        except Exception as e:
            return json.dumps({"status": "error", "error_message": f"Failed to persist CSV artifact: {e}"})

    @staticmethod
    def _create_chart(csv_path: str, chart_type: str, x: str, y: str) -> str:
        try:
            df = pd.read_csv(csv_path)
            labels = df[x].tolist()
            values = df[y].tolist()

            chart_config: Dict[str, Any] = {
                "type": chart_type,
                "data": {
                    "labels": labels,
                    "datasets": [
                        {
                            "label": y,
                            "data": values,
                            "backgroundColor": "rgba(75, 192, 192, 0.2)",
                            "borderColor": "rgba(75, 192, 192, 1)",
                            "borderWidth": 1,
                        }
                    ],
                },
                "options": {
                    "scales": {"y": {"beginAtZero": True}},
                    "plugins": {"legend": {"display": True}},
                    "responsive": True,
                    "maintainAspectRatio": False,
                },
            }

            if chart_type == "pie":
                chart_config["data"]["datasets"][0].pop("borderColor", None)
                chart_config["data"]["datasets"][0].pop("borderWidth", None)
                chart_config["data"]["datasets"][0]["backgroundColor"] = [
                    "rgba(255, 99, 132, 0.2)",
                    "rgba(54, 162, 235, 0.2)",
                    "rgba(255, 206, 86, 0.2)",
                    "rgba(75, 192, 192, 0.2)",
                    "rgba(153, 102, 255, 0.2)",
                ]
            return json.dumps(chart_config)
        except Exception as e:
            return str(e)

    def retrieval(self, query: str) -> str:
        try:
            docs = self.retriever.invoke(query)
            return "\n\n".join([d.page_content for d in docs])
        except Exception as e:
            if "401" in str(e):
                self.authenticate()
                self.initialize_clients()
                docs = self.retriever.invoke(query)
                return "\n\n".join([d.page_content for d in docs])
            return str(e)

    def run_sql(self, sql: str) -> str:
        return self._execute_query(sql)

    def visualize(self, csv_path: str, chart_type: str, x: str, y: str) -> str:
        return ToolsManager._create_chart(csv_path, chart_type, x, y)

    def cleanup(self):
        print("Cleaning up resources...")
        self.oc1_delta_conn.check_connection()
        self.oc1_delta_conn.close()


def register_tools(mcp, tools: ToolsManager) -> None:
    @mcp.tool(
        name="retrieval",
        description=(
            "Retriever for CDI/COMPUTE_DATA database schema docs including tables, columns, usage "
            "and cross table relationships. Also retrieves Compute Domain context from documentation "
            "about various services and projects in OCI."
        )
    )
    def retrieval( query: Annotated[str, Field(..., description="Natural language query to retrieve relevant docs/schema snippets.")]) -> str:
        return tools.retrieval(query)

    @mcp.tool(
        name="run_sql",
        description="Execute a Spark SQL query on the Delta Lake database and return JSON string.",
    )
    def run_sql(sql: Annotated[str, Field(..., description="Spark SQL query to run against the Delta Lake database.")]) -> str:
        return tools.run_sql(sql)

    @mcp.tool(
        name="visualize",
        description="Generate Chart.js configuration JSON from a CSV artifact path produced by run_sql.",
    )
    def visualize(
        csv_path: Annotated[str, Field(..., description="Path to the CSV artifact generated by the latest run_sql tool call.")],
        chart_type: Annotated[str, Field(..., description="Chart type to generate: 'bar'|'line'|'pie'.")],
        x: Annotated[str, Field(..., description="Column name to use for x-axis labels or pie labels.")],
        y: Annotated[str, Field(..., description="Column name to use for y-axis values.")],
    ) -> str:
        return tools.visualize(csv_path, chart_type, x, y)
